# Generated by Django 5.1 on 2024-12-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='tags',
            new_name='category',
        ),
    ]
