# Generated by Django 5.1 on 2024-12-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogpost_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='url',
            new_name='slug',
        ),
    ]
